language: python
dist: xenial

# Download jadx decompiler
before_script:
  - wget https://github.com/skylot/jadx/releases/download/v1.0.0/jadx-1.0.0.zip -O /tmp/jadx-1.0.0.zip
  - unzip /tmp/jadx-1.0.0.zip -d jadx-1.0.0
  - export PATH=$PATH:$PWD/jadx-1.0.0/bin

python:
  - "3.6"
  - "3.7"
  - "3.5"
  - "3.8"
#  - "pypy3"  # matplotlib does not compile
#  - "3.4"  # Disabled due to LXML compile error on 3.4
#  - "3.8-dev"  # Disabled due to LXML compile error on 3.8
# command to install dependencies
install:
  - "pip install .[tests,docs,magic]"
# command to run tests
script:
  - nosetests --with-coverage --with-timer --timer-top-n 50 --logging-level CRITICAL
  - python setup.py build_sphinx

after_success:
  - codecov
